title: Diving Toolkit
description: Operational calculators, emergency tools, familiarisations and reference material
baseurl: ""
url: "https://mark-lss.github.io"

markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
